<?php
$version = "0.0.0";

echo "\n<!--\n";
echo "Automatically Generated by\n";
echo "Super Engine Version $version\n\n";
echo "  /||||||\\\n";
echo " /||||||||\\\n";
echo "/||||||||||\\\n";
echo "\\||||||||||/------\\\n";
echo " \\||||||||/--------\\\n";
echo "  \\||||||/----------\\\n";
echo "  /      \\----------/\n";
echo " /        \\--------/\n";
echo "/          \\------/\n";
echo "\\          /\n";
echo " \\        /\n";
echo "  \\      /\n";
echo "\n(This is an attempt at a logo.)\n";
echo "-->";
?>
